on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: usama2490/lintly-flake8-github-action@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          failIf: any
          args: "--ignore=E121,E123 ."
